# Auth Controller
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "nomeUsuario": "joaoManager2",
  "nome": "João Manager2",
  "senha": "123456",
  "email": "joaoManager2@mail.com",
  "role": "MANAGER"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "nomeUsuario": "joaoManager1",
  "senha": "123456"
}

### Logout
POST http://localhost:3000/auth/logout

### Remember user
POST http://localhost:3000/auth/remember

### Produtos Controller
POST http://localhost:3000/produtos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsIm5vbWVVc3VhcmlvIjoiam9hb01hbmFnZXIxIiwicm9sZSI6Ik1BTkFHRVIiLCJpYXQiOjE3NTAxMzU4NTQsImV4cCI6MTc1MDEzOTQ1NH0.uvBVOPsgEtKDkRXhWCQMVdpzAtAj5CfMJ7ZZ6gt-ERM

{
  "nome": "Rucula",
  "preco": 3.00,
  "emailEmpresa": "verduraPedro@example.com",
  "dataValidade": "2025-08-31",
  "categoriaId": 2,
  "lojaId": 2

}

### Find ALL PRODUCTS
GET http://localhost:3000/produtos

### Find one product
GET http://localhost:3000/produtos/1

### Update one product
PATCH http://localhost:3000/produtos/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5vbWVVc3VhcmlvIjoiam9hb01hbmFnZXIiLCJyb2xlIjoiTUFOQUdFUiIsImlhdCI6MTc0OTYwODA4NywiZXhwIjoxNzQ5NjExNjg3fQ.BFnbdYcLptAVzjLn47RXghnmZGtQ9io4zkjnULxrkAc

{
  "nome": "Banana Prata"
}

### Delete product
DELETE http://localhost:3000/produtos/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsIm5vbWVVc3VhcmlvIjoiam9hb01hbmFnZXIxIiwicm9sZSI6Ik1BTkFHRVIiLCJpYXQiOjE3NTAwODgzNDgsImV4cCI6MTc1MDA5MTk0OH0.3Md0VZvD2DeCGCC6oqvOTMTWhwZN5ECKhiQWqnrEqd8

### Categorias Controller
POST http://localhost:3000/categorias
Content-Type: application/json

{
  "nome": "Verduras",
  "ativa": true
}

### Find all categorias
GET http://localhost:3000/categorias

### Find one categoria
GET http://localhost:3000/categorias/1

### Update categoria
PATCH http://localhost:3000/categorias/1
Content-Type: application/json

{
  "nome": "Frutas"
}

### Delete categoria
DELETE http://localhost:3000/categorias/1

### Loja Controller
POST http://localhost:3000/loja
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsIm5vbWVVc3VhcmlvIjoiam9hb01hbmFnZXIyIiwicm9sZSI6Ik1BTkFHRVIiLCJpYXQiOjE3NTAwODk1OTEsImV4cCI6MTc1MDA5MzE5MX0.fUlE6lN2wFTWsHskoevEOBdVNURDL4zTboqNelCwp8o

{
  "cnpj": 12345678901234,
  "nome": "Verduraria do Pedro",
  "horarioFuncionamento": "06:00 - 20:00",
  "endereco": "Avenida Exemplo, 123",
  "userId": 6
}

### Find all lojas
GET http://localhost:3000/loja

### Find one loja
GET http://localhost:3000/loja/1

### Update loja
PATCH http://localhost:3000/loja/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5vbWVVc3VhcmlvIjoiam9hb01hbmFnZXIiLCJyb2xlIjoiTUFOQUdFUiIsImlhdCI6MTc0OTYwODA4NywiZXhwIjoxNzQ5NjExNjg3fQ.BFnbdYcLptAVzjLn47RXghnmZGtQ9io4zkjnULxrkAc

{
  "nome": "Frutaria do João"
}

### Delete loja
DELETE http://localhost:3000/loja/1

### Add produto to loja
POST http://localhost:3000/loja/1/produtos/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5vbWVVc3VhcmlvIjoiam9hb01hbmFnZXIiLCJyb2xlIjoiTUFOQUdFUiIsImlhdCI6MTc0OTYwODA4NywiZXhwIjoxNzQ5NjExNjg3fQ.BFnbdYcLptAVzjLn47RXghnmZGtQ9io4zkjnULxrkAc

### Cliente Controller
POST http://localhost:3000/cliente
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5vbWVVc3VhcmlvIjoiam9hb1VzZXIiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc1MDEzMDI5MSwiZXhwIjoxNzUwMTMzODkxfQ.WacFiwo64P9q_20tlkIIq-NmxBZ1McdJlZoL2176Svw

{
  "dataNascimento": "1990-01-01",
  "celular": 123456789,
  "endereco": "Rua Cliente, 456",
  "cpf": 12345678901,
  "userId": 1
}

### Find all clientes
GET http://localhost:3000/cliente

### Find one cliente
GET http://localhost:3000/cliente/1

### Update cliente
PATCH http://localhost:3000/cliente/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsIm5vbWVVc3VhcmlvIjoiam9hb1VzZXIiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc0OTYwNzg2MywiZXhwIjoxNzQ5NjExNDYzfQ.vQzxgCcyVduIK8bTaybbAFsg9XOJEL-nh33QT0GfumA

{
  "endereco": "Rua Atualizada, 789"
}

### Delete cliente
DELETE http://localhost:3000/cliente/1

### Favoritar loja
POST http://localhost:3000/cliente/1/loja/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsIm5vbWVVc3VhcmlvIjoiam9hb1VzZXIiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc0OTYwNzg2MywiZXhwIjoxNzQ5NjExNDYzfQ.vQzxgCcyVduIK8bTaybbAFsg9XOJEL-nh33QT0GfumA

### New Cart
POST http://localhost:3000/carts/newCart
Content-Type: application/json

{
  "createCartDto": {
    "clienteId": 1,
    "lojaId": 2
  },
  "produtoId": 4
}

### Get one cart
GET http://localhost:3000/carts/1

### Create Cart Item
POST http://localhost:3000/cart-items
Content-Type: application/json

{
  "quantity": 1,
  "produtoId": 5,
  "cartId": 1
}


