###

GET http://localhost:3000/produtos HTTP/1.1

###

GET http://localhost:3000/produtos/3 HTTP/1.1

###

POST http://localhost:3000/produtos HTTP/1.1 
Content-Type: application/json

{
    "nome": "Produto 1",
    "preco": 9.01,
    "emailEmpresa": "teste@mail.com",
    "dataValidade": "2025-06-12",
    "categoria": 1
}

### 
PATCH http://localhost:3000/produtos/1 HTTP/1.1
Content-Type: application/json

{
    "nome": "Produto 42",
    "preco": 9.98
}

### 

DELETE http://localhost:3000/produtos/1 HTTP/1.1

#####################################################################
### Categorias

GET http://localhost:3000/categorias HTTP/1.1

###

GET http://localhost:3000/categorias/1 HTTP/1.1

###

POST http://localhost:3000/categorias HTTP/1.1 
Content-Type: application/json

{
    "nome": "Categoria 1",
    "ativa": false
}

### 
PATCH http://localhost:3000/categorias/1 HTTP/1.1
Content-Type: application/json

{
    "nome": "Categoria 7",
    "ativa": true
}

### 

DELETE http://localhost:3000/categorias/2 HTTP/1.1



####################################
### Requisições para teste do módulo de autenticação

### Realizar registro

POST http://localhost:3000/auth/register 
Content-Type: application/json

{
    "nomeUsuario":"diego3",
    "nome":"Diego Rod3",
    "senha":"123456",    
    "email":"diego2@mail.com"
}

### Realizar login

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "nomeUsuario":"diego3","senha":"123456"
}

### Inserir sem token válido (Erro)

POST http://localhost:3000/produtos HTTP/1.1 
Content-Type: application/json

{
    "nome": "Produto 101",
    "preco": 7.78,
    "emailEmpresa": "mail@mail.com",
    "dataValidade": "2025-06-14",
    "categoria": 1
}

### Inserir com token válido

POST http://localhost:3000/produtos HTTP/1.1 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsIm5vbWVVc3VhcmlvIjoiZGllZ28zIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzQ3NTc1OTY1LCJleHAiOjE3NDc1Nzk1NjV9.MzZ5y9ztbWjrQ0Ta3RXKFx8zm8DWmBShbUuc8thYYq0

{
    "nome": "Produto 19 pelo diego2",
    "preco": 2.18,
    "emailEmpresa": "mail@mail.com",
    "dataValidade": "2025-06-18",
    "categoriaId": 2
}

###########################################################################
### EXEMPLOS DE ROTAS UTILIZADAS PARA IMPLEMENTAÇÃO DE "AUTORIZAÇÃO"

### Realizar registro

POST http://localhost:3000/auth/register 
Content-Type: application/json

{
    "nomeUsuario":"joaoManagerOFC",
    "nome":"Joao ManagerOFC",
    "senha":"123456",    
    "email":"joao2@mail.com",
    "role": "MANAGER"
}

### Realizar login

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "nomeUsuario":"joaoManagerOFC","senha":"123456"
}

### 

GET http://localhost:3000/produtos HTTP/1.1

### Listar todos os produtos com categoria definida

GET http://localhost:3000/produtos/?categoria=2 HTTP/1.1

### Listar produto específico

GET http://localhost:3000/produtos/16 HTTP/1.1

### Editar produto utilizando token válido

PATCH http://localhost:3000/produtos/3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsIm5vbWVVc3VhcmlvIjoiZGllZ28yIiwicm9sZSI6Ik1BTkFHRVIiLCJpYXQiOjE3NDc1OTUxODYsImV4cCI6MTc0NzU5ODc4Nn0.-Fi4mRWbRF5RU3-awsje-OzaaSkmOJPfzBnKK7EAtxM

{
    "nome": "Produto 103 alterado",
    "preco": 9.02
}

### Remover produto utilizando token válido

DELETE http://localhost:3000/produtos/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsIm5vbWVVc3VhcmlvIjoiZGllZ28zIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzQ3NTc1ODQyLCJleHAiOjE3NDc1Nzk0NDJ9.FdQaASb1qXwApZ8Ea7fPSw9-n5GLrnzx929EPx-cgeU



### Criar loja autenticado

POST http://localhost:3000/loja HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE0LCJub21lVXN1YXJpbyI6ImpvYW9NYW5hZ2VyT0ZDIiwicm9sZSI6Ik1BTkFHRVIiLCJpYXQiOjE3NDk1ODE3MTcsImV4cCI6MTc0OTU4NTMxN30.ZhcBV9jqiF6MV_5RWH3YDPEyLTElkeQYx3IQtkMl6iQ

{
    "cnpj": 43210987654321,
    "nome": "Frutaria do João Manager",
    "horarioFuncionamento": "Ter-Sex / 06:00-18:00",
    "endereco": "Rua 2 sul",
    "userId": 14
}

### Buscar todas as lojas

GET http://localhost:3000/loja HTTP/1.1

### Buscar loja específica

GET http://localhost:3000/loja/2 HTTP/1.1

### Adicionar produto à loja

POST http://localhost:3000/loja/1/produtos/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE0LCJub21lVXN1YXJpbyI6ImpvYW9NYW5hZ2VyT0ZDIiwicm9sZSI6Ik1BTkFHRVIiLCJpYXQiOjE3NDk1ODYyMDQsImV4cCI6MTc0OTU4OTgwNH0.5qMgDB8_gA2ETGz4pwjnPxkaAH6WuiTE7WkT2l6G5ok