# Auth Controller
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "nomeUsuario": "joaoUser",
  "nome": "João User",
  "senha": "123456",
  "email": "joaoUser@mail.com",
  "role": "USER"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "nomeUsuario": "joaoManager",
  "senha": "123456"
}

### Logout
POST http://localhost:3000/auth/logout

### Remember user
POST http://localhost:3000/auth/remember

### Produtos Controller
POST http://localhost:3000/produtos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsIm5vbWVVc3VhcmlvIjoiam9hb1VzZXIiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc0OTYwNzg2MywiZXhwIjoxNzQ5NjExNDYzfQ.vQzxgCcyVduIK8bTaybbAFsg9XOJEL-nh33QT0GfumA

{
  "nome": "Produto 1",
  "preco": 9.99,
  "emailEmpresa": "empresa@example.com",
  "dataValidade": "2025-12-31",
  "categoriaId": 1
}

### Find ALL PRODUCTS
GET http://localhost:3000/produtos

### Find one product
GET http://localhost:3000/produtos/1

### Update one product
PATCH http://localhost:3000/produtos/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5vbWVVc3VhcmlvIjoiam9hb01hbmFnZXIiLCJyb2xlIjoiTUFOQUdFUiIsImlhdCI6MTc0OTYwODA4NywiZXhwIjoxNzQ5NjExNjg3fQ.BFnbdYcLptAVzjLn47RXghnmZGtQ9io4zkjnULxrkAc

{
  "nome": "Banana Prata"
}

### Delete product
DELETE http://localhost:3000/produtos/1

### Categorias Controller
POST http://localhost:3000/categorias
Content-Type: application/json

{
  "nome": "Categoria 1",
  "ativa": true
}

### Find all categorias
GET http://localhost:3000/categorias

### Find one categoria
GET http://localhost:3000/categorias/1

### Update categoria
PATCH http://localhost:3000/categorias/1
Content-Type: application/json

{
  "nome": "Frutas"
}

### Delete categoria
DELETE http://localhost:3000/categorias/1

### Loja Controller
POST http://localhost:3000/loja
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5vbWVVc3VhcmlvIjoiam9hb01hbmFnZXIiLCJyb2xlIjoiTUFOQUdFUiIsImlhdCI6MTc0OTYwODA4NywiZXhwIjoxNzQ5NjExNjg3fQ.BFnbdYcLptAVzjLn47RXghnmZGtQ9io4zkjnULxrkAc

{
  "cnpj": 12345678901234,
  "nome": "Loja 1",
  "horarioFuncionamento": "08:00 - 18:00",
  "endereco": "Rua Exemplo, 123",
  "userId": 1
}

### Find all lojas
GET http://localhost:3000/loja

### Find one loja
GET http://localhost:3000/loja/1

### Update loja
PATCH http://localhost:3000/loja/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5vbWVVc3VhcmlvIjoiam9hb01hbmFnZXIiLCJyb2xlIjoiTUFOQUdFUiIsImlhdCI6MTc0OTYwODA4NywiZXhwIjoxNzQ5NjExNjg3fQ.BFnbdYcLptAVzjLn47RXghnmZGtQ9io4zkjnULxrkAc

{
  "nome": "Frutaria do João"
}

### Delete loja
DELETE http://localhost:3000/loja/1

### Add produto to loja
POST http://localhost:3000/loja/1/produtos/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5vbWVVc3VhcmlvIjoiam9hb01hbmFnZXIiLCJyb2xlIjoiTUFOQUdFUiIsImlhdCI6MTc0OTYwODA4NywiZXhwIjoxNzQ5NjExNjg3fQ.BFnbdYcLptAVzjLn47RXghnmZGtQ9io4zkjnULxrkAc

### Cliente Controller
POST http://localhost:3000/cliente
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsIm5vbWVVc3VhcmlvIjoiam9hb1VzZXIiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc0OTYwNzg2MywiZXhwIjoxNzQ5NjExNDYzfQ.vQzxgCcyVduIK8bTaybbAFsg9XOJEL-nh33QT0GfumA

{
  "dataNascimento": "1990-01-01",
  "celular": 123456789,
  "endereco": "Rua Cliente, 456",
  "cpf": 12345678901,
  "userId": 2
}

### Find all clientes
GET http://localhost:3000/cliente

### Find one cliente
GET http://localhost:3000/cliente/1

### Update cliente
PATCH http://localhost:3000/cliente/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsIm5vbWVVc3VhcmlvIjoiam9hb1VzZXIiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc0OTYwNzg2MywiZXhwIjoxNzQ5NjExNDYzfQ.vQzxgCcyVduIK8bTaybbAFsg9XOJEL-nh33QT0GfumA

{
  "endereco": "Rua Atualizada, 789"
}

### Delete cliente
DELETE http://localhost:3000/cliente/1

### Favoritar loja
POST http://localhost:3000/cliente/1/loja/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsIm5vbWVVc3VhcmlvIjoiam9hb1VzZXIiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc0OTYwNzg2MywiZXhwIjoxNzQ5NjExNDYzfQ.vQzxgCcyVduIK8bTaybbAFsg9XOJEL-nh33QT0GfumA